"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ImageTag;
(function (ImageTag) {
    ImageTag["logo"] = "logo";
    ImageTag["white_pawn"] = "white_pawn";
    ImageTag["black_pawn"] = "black_pawn";
    ImageTag["white_knight"] = "white_knight";
    ImageTag["black_knight"] = "black_knight";
    ImageTag["white_bishop"] = "white_bishop";
    ImageTag["black_bishop"] = "black_bishop";
    ImageTag["white_rook"] = "white_rook";
    ImageTag["black_rook"] = "black_rook";
    ImageTag["white_queen"] = "white_queen";
    ImageTag["black_queen"] = "black_queen";
    ImageTag["white_king"] = "white_king";
    ImageTag["black_king"] = "black_king";
    ImageTag["select_light"] = "select_light";
    ImageTag["option_light"] = "option_light";
    ImageTag["pointGreen"] = "pointGreen";
    ImageTag["pointRed"] = "pointRed";
    ImageTag["pointYellow"] = "pointYellow";
    ImageTag["squareBlue"] = "squareBlue";
    ImageTag["squareGreen"] = "squareGreen";
    ImageTag["squareRed"] = "squareRed";
    ImageTag["btnGreen"] = "btnGreen";
    ImageTag["btnGreenPress"] = "btnGreenPress";
    ImageTag["btnPrompt"] = "btnPrompt";
    ImageTag["btnPromptPress"] = "btnPromptPress";
    ImageTag["null"] = "";
})(ImageTag = exports.ImageTag || (exports.ImageTag = {}));
//# sourceMappingURL=ImageTag.js.map