export enum ChessGameStateEnum {
    WHITE_WIN_TIME = 0,
    WHITE_WIN_CHECKMATE = 1,
    WHITE_WIN_RESIGN = 2,
    WHITE_WIN_FORFEIT = 3,

    BLACK_WIN_TIME = 10,
    BLACK_WIN_CHECKMATE = 11,
    BLACK_WIN_RESIGN = 12,
    BLACK_WIN_FORFEIT = 13,

    DRAW_STALEMATE = 20,
    DRAW_INSUFFICIENT_MATERIAL = 21,
    DRAW_50MOVES = 22,
    DRAW_REPETITION = 23,
    DRAW_AGREEMENT = 24,

    NORMAL = 30,
};
